### ISSUE TITLE
[Enhancement Suggestion] Mogelijk functienaam veranderen?

### ISSUE THREAD

**Issue by ThijmenMaus** [niels-bosman/license-plate#1]
Hi Niels, ik zag dit in mijn GitHub feed en ik besloot even een kijkje te nemen.

Misschien is het een idee om de functie `from()` te noemen ipv `make()`? Gezien dat je de License Plate "maakt door middel van" de input string?

Verder leuke en handige package! :)

**Comment by niels-bosman** [comment]
@ThijmenMaus Goede suggestie! Ik zal hem z.sm. meenemen :).

Thanks!
