### ISSUE TITLE
Rekening houden met speciale regeling rondom kentekenplaten

### ISSUE THREAD

**Issue by ThijmenMaus** [niels-bosman/license-plate#3]
Mocht je nog tijd over hebben, je vervelen of graag even wat wilt doen om deze library mogelijk te verbeteren. Misschien is het dan leuk om het volgende te implementeren:

https://www.rdw.nl/particulier/voertuigen/auto/de-kentekenplaat/cijfers-en-letters-op-de-kentekenplaat#:~:text=Verboden%20lettercombinaties&text=De%20letter%20C%20en%20Q,%2C%20PVV%2C%20SGP%20en%20VVD.

(Denk hierbij aan verboden tekens, combinaties en dergelijke).

Bijv:
**A:**
```ts
const isValid = (strict = true) => {
   /* conditoneel strict checking, standaard aan */
}
``` 
of **B:**
```ts
const isValidStrict = () => {
  /* als aparte functie */
}
```

Bij optie **A** kan de gebruiker kiezen of hij de niet strenge controle uit wilt zetten, maar is bij default aan. Optie **B** is gewoon een aparte functie, wat handig te gebruiken is.

Het is maar een idee, doe ermee wat je wilt! 😃

**Comment by niels-bosman** [comment]
@ThijmenMaus https://github.com/niels-bosman/license-plate/pull/4
