### ISSUE TITLE
Forbidden words wrong validation

### ISSUE THREAD

**Issue by stolktech** [niels-bosman/license-plate#5]
The current license plates forbidden words filter is incorrect, because you strip the dashes before the forbidden words check.

SS/SD/GVD are not allowed, but with dashes they are:
01-GVD-1 is forbidden, but 10-XG-VD is an existing license plate and should be allowed. Is this something you can update?

**Comment by niels-bosman** [comment]
Thanks for the issue. Will fix this ASAP. 😄

**Comment by brinkie** [comment]
Some clarification: xS-Dx-nn, xS-Sx-nn, nn-xS-Dx and nn-xS-Sx are all blocked but should be (and are) allowed, for example JS-DF-11 and 10-XS-SX.

Also the blocks for abbreviations for political parties have been set after the licence plates have been issued and people started to complain. For example the package blocks the use of VVD but 14-VVD-4 is a valid registration of a VW Transporter.

**Comment by niels-bosman** [comment]
@brinkie If there are cars that include abbreviations of politcal parties, they should not be in the forbidden word list. Do you agree?

**Comment by niels-bosman** [comment]
@brinkie @stolktech Could you check out https://github.com/niels-bosman/license-plate/pull/6?

**Comment by niels-bosman** [comment]
@brinkie @stolktech You can use version 1.5.2, bug is fixed there.
